repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]
        files: ^bin/ltbox/lang/.*\.json$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^(bin|tests)/
      - id: ruff-format
        files: ^(bin|tests)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        files: ^(bin|tests)/.*\.py$
        pass_filenames: true
        additional_dependencies: [types-cachetools]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: python
        args: ["-m", "pytest", "-q", "tests/", "-m", "not integration"]
        pass_filenames: false
        files: ^(bin|tests)/.*\.py$
