name: Lint Code

on:
  push:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
  pull_request:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python & Dependencies
        uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.14'

      - name: Run Ruff (Linter & isort)
        run: |
          ruff check bin/ltbox tests

      - name: Run Ruff (Formatter)
        run: |
          ruff format --check bin/ltbox tests

      - name: Run Mypy (Type Check)
        run: |
          mypy bin/ltbox tests --ignore-missing-imports
