name: Lint Code

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.python_ci }}
    steps:
      - uses: actions/checkout@v6
      - id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: .github/path-filters.yml

  lint:
    if: ${{ needs.changes.outputs.should_run == 'true' }}
    needs: changes
    uses: ./.github/workflows/python-command.yml
    with:
      task: lint
